# Generated by Django 3.0.6 on 2020-07-06 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoreGood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OrderDate', models.DateField()),
                ('CustomerID', models.CharField(max_length=25)),
                ('Sales', models.DecimalField(decimal_places=2, max_digits=6)),
                ('ProductName', models.TextField()),
                ('CustomerName', models.CharField(max_length=64)),
                ('State', models.CharField(max_length=25)),
            ],
        ),
    ]
