# Generated by Django 3.0.6 on 2020-07-06 01:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storegood',
            name='Category',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
